version: "3"
services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    environment:
      - SERVICES=s3,sqs,lambda
      - PERSISTENCE=1
      - AWS_ACCESS_KEY_ID=1234
      - AWS_SECRET_ACCESS_KEY=1234
      - AWS_DEFAULT_REGION=sa-east-1
      - AWS_DEFAULT_OUTPUT=json
    ports:
      - "4566:4566"
    volumes:
      - "./.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
